In [11]:
import pandas as pd
import numpy as np

### Importation des fichiers de données et transformation en dataframe

In [12]:
from pathlib import Path

# On part du dossier où se trouve le notebook, puis on remonte d'un niveau pour atteindre la racine du projet.
root_path = Path.cwd().parent 

# 2. Définir le chemin vers le dossier des données
data_folder = root_path / "data/raws"

print(f"🔍 Recherche des données dans : {data_folder}")

# 3. Créer un dictionnaire pour stocker nos DataFrames
# Clé = nom du fichier, Valeur = DataFrame chargé
all_dataframes = {}

# 4. Vérifier si le dossier existe
if data_folder.exists() and data_folder.is_dir():
    
    # On cherche tous les fichiers finissant par .csv dans le dossier data
    csv_files = list(data_folder.glob("*.csv"))
    
    if not csv_files:
        print("⚠️ Aucun fichier CSV trouvé dans le dossier 'data'.")
    else:
        print(f"✅ {len(csv_files)} fichiers trouvés. Chargement en cours...")
        
        for file_path in csv_files:
            try:
                # On utilise le nom du fichier (sans l'extension) comme clé
                df_name = file_path.stem 
                
                # Chargement du CSV
                df = pd.read_csv(file_path)
                
                # Stockage dans notre dictionnaire
                all_dataframes[df_name] = df
                
                print(f"   👉 {file_path.name} chargé ({len(df)} lignes)")
                
            except Exception as e:
                print(f"   ❌ Erreur sur {file_path.name} : {e}")
                
        print("\n✨ Chargement terminé !")
else:
    print(f"❌ Le dossier '{data_folder}' est introuvable. Vérifie ton arborescence.")

🔍 Recherche des données dans : c:\Users\johan\VS Code Wild 2\BRIEF_FAO_DataLab_Analyse_mondiale_de_la_sécurité_alimentaire\data\raws
✅ 6 fichiers trouvés. Chargement en cours...
   👉 bilan alimentaire 2023.csv chargé (177 lignes)
   👉 culture et produits animaux 2023.csv chargé (44846 lignes)
   👉 données de la sécurité alimentaire 2023.csv chargé (11680 lignes)
   👉 indicateurs macro 2023.csv chargé (11870 lignes)
   👉 valeur de la production agricole 2023.csv chargé (39735 lignes)
   👉 égalité des genres 2023.csv chargé (13657 lignes)

✨ Chargement terminé !

### Analyse descriptive

In [13]:
print("👀 Inspection visuelle des premières lignes\n")
print("=" * 60)

for name, df in all_dataframes.items():
    print(f"📂 FICHIER : {name}")
    print(f"📏 Dimensions : {df.shape[0]} lignes, {df.shape[1]} colonnes")
    print("-" * 30)
    
    # Affichage des 5 premières lignes
    # On utilise display() pour une belle présentation dans le notebook
    display(df.head(10))
    
    print("\n" + "=" * 60 + "\n")

👀 Inspection visuelle des premières lignes

============================================================
📂 FICHIER : bilan alimentaire 2023
📏 Dimensions : 177 lignes, 15 colonnes
------------------------------

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (FBS),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FBS,Bilans Alimentaires (2010-),4,Afghanistan,511,Population totale,S2501,Population,2023,2023,1000 No,41454.76,X,Valeur de source externe,NaN
1,FBS,Bilans Alimentaires (2010-),710,Afrique du Sud,511,Population totale,S2501,Population,2023,2023,1000 No,63212.38,X,Valeur de source externe,NaN
2,FBS,Bilans Alimentaires (2010-),8,Albanie,511,Population totale,S2501,Population,2023,2023,1000 No,2811.66,X,Valeur de source externe,NaN
3,FBS,Bilans Alimentaires (2010-),12,Algérie,511,Population totale,S2501,Population,2023,2023,1000 No,46164.22,X,Valeur de source externe,NaN
4,FBS,Bilans Alimentaires (2010-),276,Allemagne,511,Population totale,S2501,Population,2023,2023,1000 No,84548.23,X,Valeur de source externe,NaN
5,FBS,Bilans Alimentaires (2010-),24,Angola,511,Population totale,S2501,Population,2023,2023,1000 No,36749.91,X,Valeur de source externe,NaN
6,FBS,Bilans Alimentaires (2010-),28,Antigua-et-Barbuda,511,Population totale,S2501,Population,2023,2023,1000 No,93.32,X,Valeur de source externe,NaN
7,FBS,Bilans Alimentaires (2010-),682,Arabie saoudite,511,Population totale,S2501,Population,2023,2023,1000 No,33264.29,X,Valeur de source externe,NaN
8,FBS,Bilans Alimentaires (2010-),32,Argentine,511,Population totale,S2501,Population,2023,2023,1000 No,45538.40,X,Valeur de source externe,NaN
9,FBS,Bilans Alimentaires (2010-),51,Arménie,511,Population totale,S2501,Population,2023,2023,1000 No,2943.39,X,Valeur de source externe,NaN

============================================================

📂 FICHIER : culture et produits animaux 2023
📏 Dimensions : 44846 lignes, 15 colonnes
------------------------------

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,QCL,Cultures et produits animaux,4,Afghanistan,5510,Production,21159.02,Abats comestibles de chameaux et autres caméli...,2023,2023,tonnes,546.95,I,Valeur imputée par une agence réceptrice,NaN
1,QCL,Cultures et produits animaux,4,Afghanistan,5320,Animaux Producteurs/Abattus,21159.02,Abats comestibles de chameaux et autres caméli...,2023,2023,Tête,20257.00,I,Valeur imputée par une agence réceptrice,NaN
2,QCL,Cultures et produits animaux,4,Afghanistan,5510,Production,21151,"Abats, comestibles, bovins, frais, réfrigérés ...",2023,2023,tonnes,11700.19,I,Valeur imputée par une agence réceptrice,NaN
3,QCL,Cultures et produits animaux,4,Afghanistan,5320,Animaux Producteurs/Abattus,21151,"Abats, comestibles, bovins, frais, réfrigérés ...",2023,2023,Tête,510557.00,E,Valeur estimée,NaN
4,QCL,Cultures et produits animaux,4,Afghanistan,5510,Production,21156,"Abats, comestibles, caprins, frais, réfrigérés...",2023,2023,tonnes,9160.27,I,Valeur imputée par une agence réceptrice,NaN
5,QCL,Cultures et produits animaux,4,Afghanistan,5320,Animaux Producteurs/Abattus,21156,"Abats, comestibles, caprins, frais, réfrigérés...",2023,2023,Tête,3633136.00,I,Valeur imputée par une agence réceptrice,NaN
6,QCL,Cultures et produits animaux,4,Afghanistan,5510,Production,21155,"Abats, comestibles, ovins, frais, réfrigérés o...",2023,2023,tonnes,20006.32,I,Valeur imputée par une agence réceptrice,NaN
7,QCL,Cultures et produits animaux,4,Afghanistan,5320,Animaux Producteurs/Abattus,21155,"Abats, comestibles, ovins, frais, réfrigérés o...",2023,2023,Tête,6415237.00,I,Valeur imputée par une agence réceptrice,NaN
8,QCL,Cultures et produits animaux,4,Afghanistan,5312,Superficie récoltée,01343,Abricots,2023,2023,ha,25374.00,A,Valeur officielle,NaN
9,QCL,Cultures et produits animaux,4,Afghanistan,5412,Rendement,01343,Abricots,2023,2023,kg/ha,6883.00,A,Valeur officielle,NaN

============================================================

📂 FICHIER : données de la sécurité alimentaire 2023
📏 Dimensions : 11680 lignes, 15 colonnes
------------------------------

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,4,Afghanistan,6121,Valeur,21010,Suffisance des apports énergétiques alimentair...,20222024,2022-2024,%,106,E,Valeur estimée,NaN
1,FS,Données de la sécurité alimentaire,4,Afghanistan,6128,Valeur,220001,Disponibilité alimentaire par habitant utilisé...,2023,2023,kcal/personne/jour,2277,E,Valeur estimée,NaN
2,FS,Données de la sécurité alimentaire,4,Afghanistan,6128,Valeur,22000,Disponibilité alimentaire par habitant utilisé...,20222024,2022-2024,kcal/personne/jour,2261,E,Valeur estimée,NaN
3,FS,Données de la sécurité alimentaire,4,Afghanistan,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2023,2023,Int$/cap,1984,X,Valeur de source externe,NaN
4,FS,Données de la sécurité alimentaire,4,Afghanistan,6121,Valeur,210041,Prévalence de la sous-alimentation (%) (moyenn...,20222024,2022-2024,%,29.7,E,Valeur estimée,NaN
5,FS,Données de la sécurité alimentaire,4,Afghanistan,6132,Valeur,210011,Nombre de personnes sous-alimentées (millions)...,20222024,2022-2024,millions de No,12.4,E,Valeur estimée,NaN
6,FS,Données de la sécurité alimentaire,4,Afghanistan,6121,Valeur,210401,Prévalence de l’insécurité alimentaire grave –...,20222024,2022-2024,%,31,E,Valeur estimée,FAO data
7,FS,Données de la sécurité alimentaire,4,Afghanistan,61211,Confidence interval: Lower bound,210401,Prévalence de l’insécurité alimentaire grave –...,20222024,2022-2024,%,24.9,E,Valeur estimée,FAO data
8,FS,Données de la sécurité alimentaire,4,Afghanistan,61212,Confidence interval: Upper bound,210401,Prévalence de l’insécurité alimentaire grave –...,20222024,2022-2024,%,37.1,E,Valeur estimée,FAO data
9,FS,Données de la sécurité alimentaire,4,Afghanistan,6121,Valeur,210401M,Prévalence de l’insécurité alimentaire grave –...,20222024,2022-2024,%,26.8,E,Valeur estimée,FAO data

============================================================

📂 FICHIER : indicateurs macro 2023
📏 Dimensions : 11870 lignes, 15 colonnes
------------------------------

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,MK,Indicateurs macro,4,Afghanistan,6224,Valeur en devise locale standardisée,22008,Produit Intérieur Brut,2023,2023,millions de MLS,1.357275e+06,X,Valeur de source externe,NaN
1,MK,Indicateurs macro,4,Afghanistan,6110,Valeur US$,22008,Produit Intérieur Brut,2023,2023,Millions d’USD,1.641675e+04,X,Valeur de source externe,NaN
2,MK,Indicateurs macro,4,Afghanistan,6119,Valeur US$ par habitant,22008,Produit Intérieur Brut,2023,2023,USD,3.960160e+02,X,Valeur de source externe,NaN
3,MK,Indicateurs macro,4,Afghanistan,6225,"Valeur en devise locale standardisée, aux prix...",22008,Produit Intérieur Brut,2023,2023,millions de MLS,1.007893e+06,X,Valeur de source externe,NaN
4,MK,Indicateurs macro,4,Afghanistan,6185,"Valeur US$ par habitant, aux prix de 2015",22008,Produit Intérieur Brut,2023,2023,USD,3.976398e+02,X,Valeur de source externe,NaN
5,MK,Indicateurs macro,4,Afghanistan,6184,"Valeur US$, aux prix de 2015",22008,Produit Intérieur Brut,2023,2023,Millions d’USD,1.648406e+04,X,Valeur de source externe,NaN
6,MK,Indicateurs macro,4,Afghanistan,61550,Croissance annuelle en devise locale standardisée,22008,Produit Intérieur Brut,2023,2023,%,5.752782e+00,X,Valeur de source externe,NaN
7,MK,Indicateurs macro,4,Afghanistan,61810,Croissance annuelle en devise locale standardi...,22008,Produit Intérieur Brut,2023,2023,%,2.710969e+00,X,Valeur de source externe,NaN
8,MK,Indicateurs macro,4,Afghanistan,6129,Croissance annuelle US$,22008,Produit Intérieur Brut,2023,2023,%,1.581485e+01,X,Valeur de source externe,NaN
9,MK,Indicateurs macro,4,Afghanistan,61290,Croissance annuelle US$ par habitant,22008,Produit Intérieur Brut,2023,2023,%,1.336774e+01,X,Valeur de source externe,NaN

============================================================

📂 FICHIER : valeur de la production agricole 2023
📏 Dimensions : 39735 lignes, 14 colonnes
------------------------------

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit (CPC),Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,QV,Valeur de la Production Agricole,4,Afghanistan,152,Production Brute 2014-2016 (millier Int$),01343,Abricots,2023,2023,1000 Int$,143046,E,Valeur estimée
1,QV,Valeur de la Production Agricole,4,Afghanistan,56,Production Brute (millier MC),01343,Abricots,2023,2023,1000 MLS,4647070,E,Valeur estimée
2,QV,Valeur de la Production Agricole,4,Afghanistan,55,Production Brute 2014-2016 (millier MC),01343,Abricots,2023,2023,1000 MLS,3894262,E,Valeur estimée
3,QV,Valeur de la Production Agricole,4,Afghanistan,152,Production Brute 2014-2016 (millier Int$),01371,Amandes non décortiquées,2023,2023,1000 Int$,338758,E,Valeur estimée
4,QV,Valeur de la Production Agricole,4,Afghanistan,56,Production Brute (millier MC),01371,Amandes non décortiquées,2023,2023,1000 MLS,12801276,E,Valeur estimée
5,QV,Valeur de la Production Agricole,4,Afghanistan,55,Production Brute 2014-2016 (millier MC),01371,Amandes non décortiquées,2023,2023,1000 MLS,14288843,E,Valeur estimée
6,QV,Valeur de la Production Agricole,4,Afghanistan,152,Production Brute 2014-2016 (millier Int$),01654,"Anis, badiane, coriandre, cumin, carvi, fenoui...",2023,2023,1000 Int$,38926,E,Valeur estimée
7,QV,Valeur de la Production Agricole,4,Afghanistan,56,Production Brute (millier MC),01654,"Anis, badiane, coriandre, cumin, carvi, fenoui...",2023,2023,1000 MLS,2016781,E,Valeur estimée
8,QV,Valeur de la Production Agricole,4,Afghanistan,55,Production Brute 2014-2016 (millier MC),01654,"Anis, badiane, coriandre, cumin, carvi, fenoui...",2023,2023,1000 MLS,3253855,E,Valeur estimée
9,QV,Valeur de la Production Agricole,4,Afghanistan,152,Production Brute 2014-2016 (millier Int$),01349.20,Autre fruit à noyau n.a.c.,2023,2023,1000 Int$,171355,E,Valeur estimée

============================================================

📂 FICHIER : égalité des genres 2023
📏 Dimensions : 13657 lignes, 22 colonnes
------------------------------

,Code Domaine,Domaine,Code zone (M49),Zone,Code Produit (SDG),Produit,Code sexe (SDG),Sexe,Code année,Année,...,Groupe Âge de population,Code activité (SDG),Activité,Code Élément,Élément,Unité,Valeur,Symbole,Description du Symbole,Note
0,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_A,Employment in agrifood systems by subindustry ...,_T,Total,2023,2023,...,All age ranges or no breakdown by age,AGR,Agriculture,6199,Valeur,1000 No,3901.88,X,Valeur de source externe,Source: ILOStat modelled estimates
1,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_A,Employment in agrifood systems by subindustry ...,M,Sexe masculin,2023,2023,...,All age ranges or no breakdown by age,AGR,Agriculture,6199,Valeur,1000 No,3575.36,X,Valeur de source externe,Source: ILOStat modelled estimates
2,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_A,Employment in agrifood systems by subindustry ...,F,Sexe féminin,2023,2023,...,All age ranges or no breakdown by age,AGR,Agriculture,6199,Valeur,1000 No,326.52,X,Valeur de source externe,Source: ILOStat modelled estimates
3,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_N,Employment in agrifood systems by subindustry ...,_T,Total,2023,2023,...,All age ranges or no breakdown by age,NON_AGR_AFS,Non-agricultural agrifood systems,6199,Valeur,1000 No,1052.73,E,Valeur estimée,Source: Modelled based on average change in AF...
4,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_N,Employment in agrifood systems by subindustry ...,M,Sexe masculin,2023,2023,...,All age ranges or no breakdown by age,NON_AGR_AFS,Non-agricultural agrifood systems,6199,Valeur,1000 No,924.76,E,Valeur estimée,Source: Modelled based on average change in AF...
5,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_N,Employment in agrifood systems by subindustry ...,F,Sexe féminin,2023,2023,...,All age ranges or no breakdown by age,NON_AGR_AFS,Non-agricultural agrifood systems,6199,Valeur,1000 No,127.96,E,Valeur estimée,Source: Modelled based on average change in AF...
6,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_T,Employment in agrifood systems by subindustry ...,_T,Total,2023,2023,...,All age ranges or no breakdown by age,AFS,Agrifood systems,6199,Valeur,1000 No,4954.61,E,Valeur estimée,Source: Estimated by FAO
7,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_T,Employment in agrifood systems by subindustry ...,M,Sexe masculin,2023,2023,...,All age ranges or no breakdown by age,AFS,Agrifood systems,6199,Valeur,1000 No,4500.12,E,Valeur estimée,Source: Estimated by FAO
8,SXS,Données de l’égalité des genres,4,Afghanistan,EMPL_SEX_AFS_T,Employment in agrifood systems by subindustry ...,F,Sexe féminin,2023,2023,...,All age ranges or no breakdown by age,AFS,Agrifood systems,6199,Valeur,1000 No,454.49,E,Valeur estimée,Source: Estimated by FAO
9,SXS,Données de l’égalité des genres,4,Afghanistan,SH_EMPL_SEX_AFS_A,Share of employment in agrifood systems out of...,_T,Total,2023,2023,...,All age ranges or no breakdown by age,AGR,Agriculture,6121,Valeur,%,51.29,E,Valeur estimée,Source: ILOStat modelled estimates

============================================================

In [17]:
print("🔍 Rapport de Qualité des Données (Taux de complétude)\n")
print("-" * 60)

# On parcourt notre dictionnaire de DataFrames
for name, df in all_dataframes.items():
    total_rows = len(df)
    
    print(f"📊 FICHIER : {name} ({total_rows} lignes)")
    print("-" * 30)
    
    # On calcule les valeurs manquantes pour chaque colonne
    null_counts = df.isnull().sum()
    
    for col in null_counts.index:
        null_count = null_counts[col]
        
        if total_rows > 0:
            # Calcul du pourcentage de données manquantes
            pct_missing = (null_count / total_rows) * 100
            
            # On prépare un affichage propre
            # Si le manque est faible, on affiche en vert (symboliquement)
            # Si le manque est élevé (> 5%), on l'alerte
            status = "✅ OK" if pct_missing < 5 else "⚠️ ALERTE"
            
            print(f"  [{status}] {col:20} : {null_count:>6} manquantes ({pct_missing:>5.2f}%)")
        else:
            print((f"  ❌ Fichier vide pour la colonne {col}"))
            
    print("\n" + "="*60 + "\n")

🔍 Rapport de Qualité des Données (Taux de complétude)

------------------------------------------------------------
📊 FICHIER : bilan alimentaire 2023 (177 lignes)
------------------------------
  [✅ OK] Code Domaine         :      0 manquantes ( 0.00%)
  [✅ OK] Domaine              :      0 manquantes ( 0.00%)
  [✅ OK] Code zone (M49)      :      0 manquantes ( 0.00%)
  [✅ OK] Zone                 :      0 manquantes ( 0.00%)
  [✅ OK] Code Élément         :      0 manquantes ( 0.00%)
  [✅ OK] Élément              :      0 manquantes ( 0.00%)
  [✅ OK] Code Produit (FBS)   :      0 manquantes ( 0.00%)
  [✅ OK] Produit              :      0 manquantes ( 0.00%)
  [✅ OK] Code année           :      0 manquantes ( 0.00%)
  [✅ OK] Année                :      0 manquantes ( 0.00%)
  [✅ OK] Unité                :      0 manquantes ( 0.00%)
  [✅ OK] Valeur               :      0 manquantes ( 0.00%)
  [✅ OK] Symbole              :      0 manquantes ( 0.00%)
  [✅ OK] Description du Symbole :      0 manquantes ( 0.00%)
  [⚠️ ALERTE] Note                 :    177 manquantes (100.00%)

============================================================

📊 FICHIER : culture et produits animaux 2023 (44846 lignes)
------------------------------
  [✅ OK] Code Domaine         :      0 manquantes ( 0.00%)
  [✅ OK] Domaine              :      0 manquantes ( 0.00%)
  [✅ OK] Code zone (M49)      :      0 manquantes ( 0.00%)
  [✅ OK] Zone                 :      0 manquantes ( 0.00%)
  [✅ OK] Code Élément         :      0 manquantes ( 0.00%)
  [✅ OK] Élément              :      0 manquantes ( 0.00%)
  [✅ OK] Code Produit (CPC)   :      0 manquantes ( 0.00%)
  [✅ OK] Produit              :      0 manquantes ( 0.00%)
  [✅ OK] Code année           :      0 manquantes ( 0.00%)
  [✅ OK] Année                :      0 manquantes ( 0.00%)
  [✅ OK] Unité                :      0 manquantes ( 0.00%)
  [✅ OK] Valeur               :    598 manquantes ( 1.33%)
  [✅ OK] Symbole              :      0 manquantes ( 0.00%)
  [✅ OK] Description du Symbole :      0 manquantes ( 0.00%)
  [⚠️ ALERTE] Note                 :  43525 manquantes (97.05%)

============================================================

📊 FICHIER : données de la sécurité alimentaire 2023 (11680 lignes)
------------------------------
  [✅ OK] Code Domaine         :      0 manquantes ( 0.00%)
  [✅ OK] Domaine              :      0 manquantes ( 0.00%)
  [✅ OK] Code zone (M49)      :      0 manquantes ( 0.00%)
  [✅ OK] Zone                 :      0 manquantes ( 0.00%)
  [✅ OK] Code Élément         :      0 manquantes ( 0.00%)
  [✅ OK] Élément              :      0 manquantes ( 0.00%)
  [✅ OK] Code Produit         :      0 manquantes ( 0.00%)
  [✅ OK] Produit              :      0 manquantes ( 0.00%)
  [✅ OK] Code année           :      0 manquantes ( 0.00%)
  [✅ OK] Année                :      0 manquantes ( 0.00%)
  [✅ OK] Unité                :      0 manquantes ( 0.00%)
  [⚠️ ALERTE] Valeur               :   2740 manquantes (23.46%)
  [✅ OK] Symbole              :      0 manquantes ( 0.00%)
  [✅ OK] Description du Symbole :      0 manquantes ( 0.00%)
  [⚠️ ALERTE] Note                 :   6919 manquantes (59.24%)

============================================================

📊 FICHIER : indicateurs macro 2023 (11870 lignes)
------------------------------
  [✅ OK] Code Domaine         :      0 manquantes ( 0.00%)
  [✅ OK] Domaine              :      0 manquantes ( 0.00%)
  [✅ OK] Code zone (M49)      :      0 manquantes ( 0.00%)
  [✅ OK] Zone                 :      0 manquantes ( 0.00%)
  [✅ OK] Code Élément         :      0 manquantes ( 0.00%)
  [✅ OK] Élément              :      0 manquantes ( 0.00%)
  [✅ OK] Code Produit         :      0 manquantes ( 0.00%)
  [✅ OK] Produit              :      0 manquantes ( 0.00%)
  [✅ OK] Code année           :      0 manquantes ( 0.00%)
  [✅ OK] Année                :      0 manquantes ( 0.00%)
  [✅ OK] Unité                :    414 manquantes ( 3.49%)
  [✅ OK] Valeur               :      0 manquantes ( 0.00%)
  [✅ OK] Symbole              :      0 manquantes ( 0.00%)
  [✅ OK] Description du Symbole :      0 manquantes ( 0.00%)
  [⚠️ ALERTE] Note                 :  11870 manquantes (100.00%)

============================================================

📊 FICHIER : valeur de la production agricole 2023 (39735 lignes)
------------------------------
  [✅ OK] Code Domaine         :      0 manquantes ( 0.00%)
  [✅ OK] Domaine              :      0 manquantes ( 0.00%)
  [✅ OK] Code zone (M49)      :      0 manquantes ( 0.00%)
  [✅ OK] Zone                 :      0 manquantes ( 0.00%)
  [✅ OK] Code Élément         :      0 manquantes ( 0.00%)
  [✅ OK] Élément              :      0 manquantes ( 0.00%)
  [✅ OK] Code Produit (CPC)   :      0 manquantes ( 0.00%)
  [✅ OK] Produit              :      0 manquantes ( 0.00%)
  [✅ OK] Code année           :      0 manquantes ( 0.00%)
  [✅ OK] Année                :      0 manquantes ( 0.00%)
  [✅ OK] Unité                :      0 manquantes ( 0.00%)
  [✅ OK] Valeur               :      0 manquantes ( 0.00%)
  [✅ OK] Symbole              :      0 manquantes ( 0.00%)
  [✅ OK] Description du Symbole :      0 manquantes ( 0.00%)

============================================================

📊 FICHIER : égalité des genres 2023 (13657 lignes)
------------------------------
  [✅ OK] Code Domaine         :      0 manquantes ( 0.00%)
  [✅ OK] Domaine              :      0 manquantes ( 0.00%)
  [✅ OK] Code zone (M49)      :      0 manquantes ( 0.00%)
  [✅ OK] Zone                 :      0 manquantes ( 0.00%)
  [✅ OK] Code Produit (SDG)   :      0 manquantes ( 0.00%)
  [✅ OK] Produit              :      0 manquantes ( 0.00%)
  [✅ OK] Code sexe (SDG)      :      0 manquantes ( 0.00%)
  [✅ OK] Sexe                 :      0 manquantes ( 0.00%)
  [✅ OK] Code année           :      0 manquantes ( 0.00%)
  [✅ OK] Année                :      0 manquantes ( 0.00%)
  [✅ OK] Niveau géographique  :      0 manquantes ( 0.00%)
  [✅ OK] Code Groupe Âge de population :      0 manquantes ( 0.00%)
  [✅ OK] Groupe Âge de population :      0 manquantes ( 0.00%)
  [✅ OK] Code activité (SDG)  :      0 manquantes ( 0.00%)
  [✅ OK] Activité             :      0 manquantes ( 0.00%)
  [✅ OK] Code Élément         :      0 manquantes ( 0.00%)
  [✅ OK] Élément              :      0 manquantes ( 0.00%)
  [✅ OK] Unité                :      0 manquantes ( 0.00%)
  [⚠️ ALERTE] Valeur               :   1727 manquantes (12.65%)
  [✅ OK] Symbole              :      0 manquantes ( 0.00%)
  [✅ OK] Description du Symbole :      0 manquantes ( 0.00%)
  [✅ OK] Note                 :    349 manquantes ( 2.56%)

============================================================

Certaines colonnes sont très peu remplies voire complètement vides, surtout les colonnes de note

In [15]:
print("🔍 Rapport de Qualité des Données (Doublons)\n")
print("-" * 60)

for name, df in all_dataframes.items():
    total_rows = len(df)
    
    # --- PARTIE 1 : Vérification des doublons parfaits ---
    duplicate_count = df.duplicated().sum()
    
    print(f"📊 FICHIER : {name} ({total_rows} lignes)")
    print(f"  [!] Doublons parfaits trouvés : {duplicate_count}")

🔍 Rapport de Qualité des Données (Doublons)

------------------------------------------------------------
📊 FICHIER : bilan alimentaire 2023 (177 lignes)
  [!] Doublons parfaits trouvés : 0
📊 FICHIER : culture et produits animaux 2023 (44846 lignes)
  [!] Doublons parfaits trouvés : 0
📊 FICHIER : données de la sécurité alimentaire 2023 (11680 lignes)
  [!] Doublons parfaits trouvés : 0
📊 FICHIER : indicateurs macro 2023 (11870 lignes)
  [!] Doublons parfaits trouvés : 0
📊 FICHIER : valeur de la production agricole 2023 (39735 lignes)
  [!] Doublons parfaits trouvés : 0
📊 FICHIER : égalité des genres 2023 (13657 lignes)
  [!] Doublons parfaits trouvés : 0

Aucun doublon parfait  
En fonction des données regardées, nous analyserons plus en détail les éventuelles lignes doublées partiellement

In [16]:
print("🔍 Rapport de Qualité des Données (Dtypes)\n")
print("-" * 60)

for name, df in all_dataframes.items():
    print(f"📊 FICHIER : {name}")
    print(f"  Total colonnes : {len(df.columns)}")
    print("-" * 30)
    
    # On récupère les types et on crée un petit tableau récapitulatif
    dtype_info = []
    for col, dtype in df.dtypes.items():
        # On compte combien de valeurs ne sont PAS nulles pour voir la réalité du type
        non_null_count = df[col].count()
        dtype_info.append({
            "Colonne": col,
            "Type actuel": dtype,
  			"Valeurs non-nulles": non_null_count
        })
    
    # Création d'un DataFrame de diagnostic pour un affichage propre
    df_diag = pd.DataFrame(dtype_info)
    
    # On affiche le tableau de diagnostic
    display(df_diag)
    
    # Alerte spécifique : On cherche les colonnes numériques qui sont en type 'object'
    # (C'est souvent là que se cachent les erreurs de lecture)
    numeric_as_object = df_diag[(df_diag['Type actuel'] == 'object') & 
                                (df_diag['Colonne'].str.contains('Valeur|Année|Code', case=False, na=False))]
    
    if not numeric_as_object.empty:
        print(f"  ⚠️ ALERTE : Colonnes numériques potentiellement mal typées :")
        for _, row in numeric_as_object.iterrows():
            print(f"     👉 {row['Colonne']} est en type '{row['Type actuel']}'")
    else:
        print("  ✅ Aucun problème de type numérique détecté.")
        
    print("\n" + "="*60 + "\n")

🔍 Rapport de Qualité des Données (Dtypes)

------------------------------------------------------------
📊 FICHIER : bilan alimentaire 2023
  Total colonnes : 15
------------------------------

                   Colonne Type actuel  Valeurs non-nulles
0             Code Domaine         str                 177
1                  Domaine         str                 177
2          Code zone (M49)       int64                 177
3                     Zone         str                 177
4             Code Élément       int64                 177
5                  Élément         str                 177
6       Code Produit (FBS)         str                 177
7                  Produit         str                 177
8               Code année       int64                 177
9                    Année       int64                 177
10                   Unité         str                 177
11                  Valeur     float64                 177
12                 Symbole         str                 177
13  Description du Symbole         str                 177
14                    Note     float64                   0

  ✅ Aucun problème de type numérique détecté.

============================================================

📊 FICHIER : culture et produits animaux 2023
  Total colonnes : 15
------------------------------

                   Colonne Type actuel  Valeurs non-nulles
0             Code Domaine         str               44846
1                  Domaine         str               44846
2          Code zone (M49)       int64               44846
3                     Zone         str               44846
4             Code Élément       int64               44846
5                  Élément         str               44846
6       Code Produit (CPC)         str               44846
7                  Produit         str               44846
8               Code année       int64               44846
9                    Année       int64               44846
10                   Unité         str               44846
11                  Valeur     float64               44248
12                 Symbole         str               44846
13  Description du Symbole         str               44846
14                    Note         str                1321

  ✅ Aucun problème de type numérique détecté.

============================================================

📊 FICHIER : données de la sécurité alimentaire 2023
  Total colonnes : 15
------------------------------

                   Colonne Type actuel  Valeurs non-nulles
0             Code Domaine         str               11680
1                  Domaine         str               11680
2          Code zone (M49)       int64               11680
3                     Zone         str               11680
4             Code Élément       int64               11680
5                  Élément         str               11680
6             Code Produit         str               11680
7                  Produit         str               11680
8               Code année       int64               11680
9                    Année         str               11680
10                   Unité         str               11680
11                  Valeur         str                8940
12                 Symbole         str               11680
13  Description du Symbole         str               11680
14                    Note         str                4761

  ✅ Aucun problème de type numérique détecté.

============================================================

📊 FICHIER : indicateurs macro 2023
  Total colonnes : 15
------------------------------

                   Colonne Type actuel  Valeurs non-nulles
0             Code Domaine         str               11870
1                  Domaine         str               11870
2          Code zone (M49)       int64               11870
3                     Zone         str               11870
4             Code Élément       int64               11870
5                  Élément         str               11870
6             Code Produit       int64               11870
7                  Produit         str               11870
8               Code année       int64               11870
9                    Année       int64               11870
10                   Unité         str               11456
11                  Valeur     float64               11870
12                 Symbole         str               11870
13  Description du Symbole         str               11870
14                    Note     float64                   0

  ✅ Aucun problème de type numérique détecté.

============================================================

📊 FICHIER : valeur de la production agricole 2023
  Total colonnes : 14
------------------------------

                   Colonne Type actuel  Valeurs non-nulles
0             Code Domaine         str               39735
1                  Domaine         str               39735
2          Code zone (M49)       int64               39735
3                     Zone         str               39735
4             Code Élément       int64               39735
5                  Élément         str               39735
6       Code Produit (CPC)         str               39735
7                  Produit         str               39735
8               Code année       int64               39735
9                    Année       int64               39735
10                   Unité         str               39735
11                  Valeur       int64               39735
12                 Symbole         str               39735
13  Description du Symbole         str               39735

  ✅ Aucun problème de type numérique détecté.

============================================================

📊 FICHIER : égalité des genres 2023
  Total colonnes : 22
------------------------------

                          Colonne Type actuel  Valeurs non-nulles
0                    Code Domaine         str               13657
1                         Domaine         str               13657
2                 Code zone (M49)       int64               13657
3                            Zone         str               13657
4              Code Produit (SDG)         str               13657
5                         Produit         str               13657
6                 Code sexe (SDG)         str               13657
7                            Sexe         str               13657
8                      Code année       int64               13657
9                           Année       int64               13657
10            Niveau géographique         str               13657
11  Code Groupe Âge de population         str               13657
12       Groupe Âge de population         str               13657
13            Code activité (SDG)         str               13657
14                       Activité         str               13657
15                   Code Élément       int64               13657
16                        Élément         str               13657
17                          Unité         str               13657
18                         Valeur     float64               11930
19                        Symbole         str               13657
20         Description du Symbole         str               13657
21                           Note         str               13308

  ✅ Aucun problème de type numérique détecté.

============================================================

Les types des colonnes sont tous corrects

In [21]:
print("📊 Analyse descriptive des distributions\n")
print("=" * 60)

for name, df in all_dataframes.items():
    print(f"📂 FICHIER : {name}")
    print("-" * 30)
    
    # On sélectionne uniquement les colonnes numériques pour le describe
    df_numeric = df.select_dtypes(include=['number'])
    
    if df_numeric.empty:
        print("  ℹ️ Pas de colonnes numériques dans ce fichier.")
    else:
        # Le describe() avec les statistiques clés
        stats = df_numeric.describe().T  # .T pour transposer et avoir un tableau lisible
        
        # On ajoute la variance pour voir l'étalement des données
        stats['variance'] = df_numeric.var()
        
        # On affiche le résultat
        display(stats[['count', 'mean', 'std', 'variance', 'min', '50%', 'max']])
        
        print("\n  💡 Note d'analyse :")
        for col in df_numeric.columns:
            col_min = df_arg_min = df_numeric[col].min()
            col_max = df_numeric[col].max()
            col_mean = df_numeric[col].mean()
            
            # Si la moyenne est très loin de la médiane (50%), il y a un déséquilibre
            if abs(col_mean - df_numeric[col].median()) > (df_numeric[col].std() * 1):
                print(f"     ⚠️ Attention sur '{col}' : La moyenne et la médiane sont très décalées. Présence probable d'asymétrie.")

    print("\n" + "=" * 60 + "\n")

📊 Analyse descriptive des distributions

============================================================
📂 FICHIER : bilan alimentaire 2023
------------------------------

,count,mean,std,variance,min,50%,max
Code zone (M49),177.0,434.248588,253.481027,6.425263e+04,4.00,430.00,894.00
Code Élément,177.0,511.000000,0.000000,0.000000e+00,511.00,511.00,511.00
Code année,177.0,2023.000000,0.000000,0.000000e+00,2023.00,2023.00,2023.00
Année,177.0,2023.000000,0.000000,0.000000e+00,2023.00,2023.00,2023.00
Valeur,177.0,51894.989379,189496.555342,3.590894e+10,9.82,9130.43,1454058.72
Note,0.0,NaN,NaN,NaN,NaN,NaN,NaN

  💡 Note d'analyse :

============================================================

📂 FICHIER : culture et produits animaux 2023
------------------------------

,count,mean,std,variance,min,50%,max
Code zone (M49),44846.0,426.663493,2.544394e+02,6.473943e+04,4.0,414.0,894.0
Code Élément,44846.0,5408.423271,1.015257e+02,1.030747e+04,5111.0,5412.0,5513.0
Code année,44846.0,2023.000000,0.000000e+00,0.000000e+00,2023.0,2023.0,2023.0
Année,44846.0,2023.000000,0.000000e+00,0.000000e+00,2023.0,2023.0,2023.0
Valeur,44248.0,930754.769125,1.295575e+07,1.678514e+14,0.0,6694.5,782058236.0

  💡 Note d'analyse :

============================================================

📂 FICHIER : données de la sécurité alimentaire 2023
------------------------------

,count,mean,std,variance,min,50%,max
Code zone (M49),11680.0,4.265376e+02,2.535393e+02,6.428218e+04,4.0,422.0,894.0
Code Élément,11680.0,2.924016e+04,2.720846e+04,7.403005e+08,6121.0,6132.0,61322.0
Code année,11680.0,1.430490e+07,9.199952e+06,8.463911e+13,2023.0,20222024.0,20222024.0

  💡 Note d'analyse :

============================================================

📂 FICHIER : indicateurs macro 2023
------------------------------

,count,mean,std,variance,min,50%,max
Code zone (M49),11870.0,4.299944e+02,2.511370e+02,6.306982e+04,4.000000,430.000000,8.940000e+02
Code Élément,11870.0,2.429951e+04,2.603772e+04,6.779630e+08,6103.000000,6187.000000,6.189000e+04
Code Produit,11870.0,2.202896e+04,2.748301e+01,7.553160e+02,22008.000000,22015.000000,2.207500e+04
Code année,11870.0,2.023000e+03,0.000000e+00,0.000000e+00,2023.000000,2023.000000,2.023000e+03
Année,11870.0,2.023000e+03,0.000000e+00,0.000000e+00,2023.000000,2023.000000,2.023000e+03
Valeur,11870.0,4.739796e+07,1.959401e+09,3.839251e+18,-84.949219,17.252094,1.430393e+11
Note,0.0,NaN,NaN,NaN,NaN,NaN,NaN

  💡 Note d'analyse :

============================================================

📂 FICHIER : valeur de la production agricole 2023
------------------------------

,count,mean,std,variance,min,50%,max
Code zone (M49),39735.0,4.257501e+02,2.581722e+02,6.665287e+04,4.0,417.0,8.940000e+02
Code Élément,39735.0,7.969354e+01,4.096817e+01,1.678391e+03,55.0,57.0,1.520000e+02
Code année,39735.0,2.023000e+03,0.000000e+00,0.000000e+00,2023.0,2023.0,2.023000e+03
Année,39735.0,2.023000e+03,0.000000e+00,0.000000e+00,2023.0,2023.0,2.023000e+03
Valeur,39735.0,5.233685e+08,1.682196e+10,2.829782e+20,0.0,49311.0,2.399762e+12

  💡 Note d'analyse :

============================================================

📂 FICHIER : égalité des genres 2023
------------------------------

,count,mean,std,variance,min,50%,max
Code zone (M49),13657.0,421.981328,257.861333,6.649247e+04,4.00,410.000,894.00
Code année,13657.0,2023.000000,0.000000,0.000000e+00,2023.00,2023.000,2023.00
Année,13657.0,2023.000000,0.000000,0.000000e+00,2023.00,2023.000,2023.00
Code Élément,13657.0,6137.675038,33.603838,1.129218e+03,6121.00,6121.000,6246.00
Valeur,11930.0,478.822882,6115.207839,3.739577e+07,-65.17,17.995,326812.75

  💡 Note d'analyse :

============================================================

indicateurs macro 2023 : colonne 'valeurs' comporte des nombres négatifs, il faut vérifier la vraisemblance  
égalité des genres 2023 : colonne 'valeurs' comporte des nombres négatifs, il faut vérifier la vraisemblance